### ISSUE TITLE
Running on a Mac

### ISSUE THREAD

**Issue by rcraggs** [gitomator/gitomator-classroom#6]
I had the same problems with gem installing nokogiri as described on the page below. I had to follow the instructions starting "Did you try running all of these commands?" to get it to install. May be worth documenting

https://github.com/wpscanteam/wpscan/issues/876

**Comment by joeyfreund** [comment]
@rcraggs , thanks for reporting the issue.

Just [added](https://github.com/gitomator/gitomator.github.io/commit/d505b58301a576f55aae95c8980df1c34b3eff69) a note to [the docs](https://gitomator.github.io/docs/quick-start/#setup).
